#!/usr/bin/env python3
"""Translate `gn desc <out_dir> //* --format=json` to BUILD.bazel files.

M2 skeleton (DESIGN.md §4.1). Groups targets by source BUILD.gn directory
and emits one BUILD.bazel per directory. Handles the six common GN target
types structurally; gaps surfaced by M3 (`bazel build //runtime/vm:libdart_vm_jit`)
get hand-fixed in the generated files.

Usage:
  tools/bazel/translate_gn_desc.py gn-desc.json --root .
"""

import argparse
import json
import os
import sys
from collections import defaultdict

HEADER = """# AUTO-GENERATED by tools/bazel/translate_gn_desc.py from `gn desc` output.
# Hand-fixes belong in this file (M3); rerun the translator to refresh structural
# bits and re-apply fixes from version control.

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_shared_library")

package(default_visibility = ["//visibility:public"])

# GN lets one target's sources reach into other BUILD.gn dirs; Bazel
# requires cross-package file refs to be explicitly exported. Bulk-export
# every file in the package so the gn-shaped source lists keep working.
exports_files(glob(
    ["**/*.h", "**/*.hpp", "**/*.hh", "**/*.inc",
     "**/*.cc", "**/*.cpp", "**/*.c", "**/*.S", "**/*.s"],
    allow_empty = True,
))

"""


def split_label(label):
    """`//foo/bar:baz` -> (`foo/bar`, `baz`).  `//foo/bar` -> (`foo/bar`, `bar`)."""
    assert label.startswith("//"), label
    body = label[2:]
    if ":" in body:
        path, name = body.split(":", 1)
    else:
        path = body
        name = os.path.basename(body) or body
    return path, name


def src_label(src_path, pkg, packages):
    """gn workspace path `//pkg/sub/foo.cc` -> Bazel src reference.

    Walks up `src_path`'s directory chain looking for the longest known
    Bazel package (any dir that has GN targets and so will get a
    BUILD.bazel). That package owns the file; emit either a relative path
    (when owning pkg == current pkg) or an absolute cross-package label.
    Generated outputs (under //out/...) get a TODO marker for M3 routing.
    """
    if src_path.startswith("//out/"):
        return f'# TODO(M3): generated {src_path}'
    assert src_path.startswith("//"), src_path
    rel = src_path[2:]
    cur = os.path.dirname(rel)
    owning_pkg = ""
    while cur:
        if cur in packages:
            owning_pkg = cur
            break
        cur = os.path.dirname(cur)
    inner = rel[len(owning_pkg) + 1:] if owning_pkg else rel
    if owning_pkg == pkg:
        return f'"{inner}"'
    return f'"//{owning_pkg}:{inner}"'


def _attr_list(name, items, indent=4):
    if not items:
        return ""
    pad = " " * indent
    body = "\n".join(f"{pad}    {x}," for x in items)
    return f"{pad}{name} = [\n{body}\n{pad}],\n"


_HDR_EXTS = (".h", ".hpp", ".hh", ".inc")


def emit_cc_library(name, t, pkg, packages):
    """source_set / static_library -> cc_library."""
    hdrs, srcs = [], []
    for s in t.get("sources", []):
        lbl = src_label(s, pkg, packages)
        (hdrs if s.endswith(_HDR_EXTS) else srcs).append(lbl)
    deps = [f'"{d}"' for d in t.get("deps", [])]
    defines = [f'"{d}"' for d in t.get("defines", [])]
    include_copts = []
    for inc in t.get("include_dirs", []):
        if inc.startswith("//out/"):
            continue  # TODO(M3): generated include dir
        path = inc[2:] if inc.startswith("//") else inc
        path = path.rstrip("/")
        if path:
            include_copts.append(f'"-I{path}"')
    copts = include_copts + \
            [f'"{c}"' for c in t.get("cflags", [])] + \
            [f'"{c}"' for c in t.get("cflags_cc", [])]
    linkopts = [f'"-l{l}"' for l in t.get("libs", [])]
    out = [f'cc_library(\n    name = "{name}",\n']
    out.append(_attr_list("srcs", srcs))
    out.append(_attr_list("hdrs", hdrs))
    out.append(_attr_list("deps", deps))
    out.append(_attr_list("defines", defines))
    out.append(_attr_list("copts", copts))
    out.append(_attr_list("linkopts", linkopts))
    out.append(")\n")
    return "".join(out)


def emit_cc_binary(name, t, pkg, packages):
    body = emit_cc_library(name, t, pkg, packages).replace("cc_library(", "cc_binary(", 1)
    return body


def emit_group(name, t, pkg, packages):
    """gn group -> cc_library with deps only.

    A gn group is a named bundle of dependencies (no sources). The closest
    Bazel primitive that propagates cc deps is a cc_library with no srcs.
    """
    deps = [f'"{d}"' for d in t.get("deps", [])]
    out = [f'cc_library(\n    name = "{name}",\n']
    out.append(_attr_list("deps", deps))
    out.append(")\n")
    return "".join(out)


def emit_stub(rule_kind):
    """Empty cc_library stub keeps the label resolvable at analysis time."""
    def _emit(name, t, pkg, packages):
        return (
            f'# TODO(M3): {rule_kind} for {name} (gn type={t["type"]})\n'
            f'cc_library(name = "{name}")\n'
        )
    return _emit


EMITTERS = {
    "source_set":     emit_cc_library,
    "static_library": emit_cc_library,
    "shared_library": emit_stub("cc_shared_library"),
    "executable":     emit_cc_binary,
    "action":         emit_stub("genrule"),
    "action_foreach": emit_stub("genrule"),
    "copy":           emit_stub("copy"),
    "group":          emit_group,
    "generated_file": emit_stub("genrule"),
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("desc_json", help="gn desc //* --format=json output")
    ap.add_argument("--root", default=".", help="Repo root for BUILD.bazel output")
    args = ap.parse_args()

    with open(args.desc_json) as f:
        desc = json.load(f)

    # Skip non-default-toolchain entries — gn desc represents them as
    # //path:name(//toolchain:tc), which is illegal in Bazel target names.
    # Multi-toolchain folding is M4 (select() blocks).
    by_pkg = defaultdict(list)
    for label, target in desc.items():
        if "(" in label:
            continue
        pkg, name = split_label(label)
        by_pkg[pkg].append((name, target))

    packages = set(by_pkg.keys())
    for pkg, targets in sorted(by_pkg.items()):
        out_path = os.path.join(args.root, pkg, "BUILD.bazel")
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w") as f:
            f.write(HEADER)
            for name, t in sorted(targets):
                emit = EMITTERS.get(t["type"])
                if emit is None:
                    f.write(f'# TODO(M3): unknown gn type {t["type"]} for {name}\n')
                    continue
                f.write(emit(name, t, pkg, packages))
                f.write("\n")
        print(f"wrote {out_path} ({len(targets)} targets)", file=sys.stderr)


if __name__ == "__main__":
    main()
