#!/usr/bin/env python3
"""Translate `gn desc <out_dir> //* --format=json` to BUILD.bazel files.

M2 skeleton (DESIGN.md §4.1). Groups targets by source BUILD.gn directory
and emits one BUILD.bazel per directory. Handles the six common GN target
types structurally; gaps surfaced by M3 (`bazel build //runtime/vm:libdart_vm_jit`)
get hand-fixed in the generated files.

Usage:
  tools/bazel/translate_gn_desc.py gn-desc.json --root .
"""

import argparse
import json
import os
import re
import sys
import textwrap
from collections import defaultdict

_GENERATED_MARKER = "AUTO-GENERATED by tools/bazel/translate_gn_desc.py"

HEADER_PREFIX = f"""# {_GENERATED_MARKER} from `gn desc` output.
# Hand-fixes belong in this file (M3); rerun the translator to refresh structural
# bits and re-apply fixes from version control.

"""

HEADER_SUFFIX = """package(default_visibility = ["//visibility:public"])

# GN lets one target's sources reach into other BUILD.gn dirs; Bazel
# requires cross-package file refs to be explicitly exported. Bulk-export
# every file in the package so the gn-shaped source lists keep working.
exports_files(glob(
    [
        "**/*.h",
        "**/*.hpp",
        "**/*.hh",
        "**/*.inc",
        "**/*.cc",
        "**/*.cpp",
        "**/*.c",
        "**/*.S",
        "**/*.s",
    ],
    allow_empty = True,
))

"""

# --- §7 overlay (opt-in) ---------------------------------------------------
# docs/todo_issues/m4_multiconfig_scoping.md §7. For a package listed here the
# translator emits its MACHINE-derived cc_* targets into a generated
# `gen_targets.bzl` macro and NEVER (over)writes BUILD.bazel — a hand-authored,
# clobber-safe BUILD.bazel load()s + calls gen_targets() and owns every
# hand-fixed target (the M4 select()s, .so rewrites, hand-wired deps, genrules,
# …). Mirrors tools/bazel/dart/gen_packages.py -> packages.bzl. Every OTHER
# package keeps emitting a single BUILD.bazel exactly as before.
#
# Which targets are machine-owned vs hand-owned is decided by NAME EXCLUSION:
# a desc target is emitted into gen_targets.bzl iff its name is NOT already
# defined in the hand-authored BUILD.bazel (the hand file is the authority on
# what it owns). GEN_TARGETS_DROP suppresses obsolete GN targets
# the hand file replaced (e.g. `copy` actions superseded by real .so rules) so a
# regen does not resurrect them.
GEN_TARGETS_PACKAGES = {"runtime/bin", "runtime/vm", "runtime/lib"}

GEN_TARGETS_DROP = {
    # Obsolete GN `copy` targets that runtime/bin/BUILD.bazel replaced with real
    # `.so` cc_binary rules (libffi_test_functions.so, …). Dropped so the macro
    # never re-emits the dead stubs.
    "runtime/bin": {
        "entrypoints_verification_test_copy",
        "ffi_test_dynamic_library_copy",
        "ffi_test_functions_copy",
    },
}

GEN_TARGETS_DOCSTRING = f'''"""{_GENERATED_MARKER} from `gn desc` output.

§7 overlay (docs/todo_issues/m4_multiconfig_scoping.md §7): the machine-derived
cc_* targets for this package. A regen overwrites THIS file freely; it never
touches the HAND-AUTHORED BUILD.bazel that load()s + calls gen_targets() and
owns the hand-fixed targets. Mirrors tools/bazel/dart/packages.bzl. DO NOT EDIT.
"""'''

FFI_CC_INCLUDES_TARGET = """
# Helper library to expose .cc files as headers for inclusion in unit_test_custom_zone.cc
# without compiling them as separate translation units (which would cause duplicate symbols).
cc_library(
    name = "ffi_cc_includes",
    hdrs = [
        "//runtime/vm:compiler/ffi/native_calling_convention.cc",
        "//runtime/vm:compiler/ffi/native_location.cc",
        "//runtime/vm:compiler/ffi/native_type.cc",
        "//runtime/vm:zone_text_buffer.cc",
    ],
)
"""


def split_label(label):
    """`//foo/bar:baz` -> (`foo/bar`, `baz`).  `//foo/bar` -> (`foo/bar`, `bar`)."""
    assert label.startswith("//"), label
    body = label[2:]
    if ":" in body:
        path, name = body.split(":", 1)
    else:
        path = body
        name = os.path.basename(body) or body
    return path, name


def canonical_label(label):
    if not label.startswith("//"):
        return label
    if "(" in label:
        return label

    # Bzlmod mapping (Option 1)
    if label == "//third_party/zlib" or label.startswith("//third_party/zlib:"):
        return label.replace("//third_party/zlib", "@zlib//")
    if label == "//third_party/icu" or label.startswith("//third_party/icu:"):
        return label.replace("//third_party/icu", "@icu//")
    if label.startswith("//third_party/icu/flutter:"):
        return label.replace("//third_party/icu/flutter:", "@icu//flutter:")
    if label == "//third_party/boringssl" or label.startswith(
            "//third_party/boringssl:"):
        return label.replace("//third_party/boringssl", "@boringssl//")
    if label == "//third_party/perfetto" or label.startswith(
            "//third_party/perfetto:"):
        return label.replace("//third_party/perfetto", "@perfetto//")

    body = label[2:]
    if ":" in body:
        path, name = body.split(":", 1)
        if os.path.basename(path) == name:
            return f"//{path}"
    return label


def make_load_statement(rules_used):
    if not rules_used:
        return ""
    rules = sorted(list(rules_used))
    rules_str = ", ".join(f'"{r}"' for r in rules)
    return f'load("//tools/bazel:rules.bzl", {rules_str})\n\n'


def get_rules_used(targets, pkg):
    rules = set()
    for name, t in targets:
        t_type = t.get("type")
        if t_type in EMITTERS:
            if t_type == "executable":
                if pkg == "runtime/bin/ffi_unit_test" and name == "run_ffi_unit_tests_x64_linux":
                    rules.add("cc_test")
                else:
                    rules.add("cc_binary")
            else:
                rules.add("cc_library")
    return rules


_ROOT = "."  # set by main(); used by src_label for on-disk existence check


def src_label(src_path, pkg, packages):
    """gn workspace path `//pkg/sub/foo.cc` -> Bazel src reference.

    Walks up `src_path`'s directory chain looking for the longest known
    Bazel package (any dir that has GN targets and so will get a
    BUILD.bazel). That package owns the file; emit either a relative path
    (when owning pkg == current pkg) or an absolute cross-package label.
    Returns None when the file is a generated output (under //out/...) or
    missing from disk — caller drops it (codegen action wiring is M5).
    """
    if src_path.startswith(("//out/", "//xcodebuild/")):
        return None
    assert src_path.startswith("//"), src_path
    rel = src_path[2:]
    if not os.path.exists(os.path.join(_ROOT, rel)):
        return None
    cur = os.path.dirname(rel)
    owning_pkg = ""
    while cur:
        if cur in packages:
            owning_pkg = cur
            break
        cur = os.path.dirname(cur)
    inner = rel[len(owning_pkg) + 1:] if owning_pkg else rel
    if owning_pkg == pkg:
        return f'"{inner}"'
    return f'"//{owning_pkg}:{inner}"'


def _attr_list(name, items, indent=4):
    if not items:
        return ""
    pad = " " * indent
    body = "\n".join(f"{pad}    {x}," for x in items)
    return f"{pad}{name} = [\n{body}\n{pad}],\n"


_HDR_EXTS = (".h", ".hpp", ".hh", ".inc")


def emit_cc_library(name, t, pkg, packages, rule="cc_library", args=None):
    """source_set / static_library -> cc_library; executable -> cc_binary.

    cc_binary has no `hdrs` attribute, so for binaries the header inputs are
    folded into `srcs` (header files in srcs are made available to the
    binary's own compiles but not compiled as translation units).
    """
    hdrs, srcs, data = [], [], []
    public_val = t.get("public", "*")
    public_headers = None
    if isinstance(public_val, list):
        public_headers = set()
        for p in public_val:
            lbl = src_label(p, pkg, packages)
            if lbl is not None:
                public_headers.add(lbl)

    for s in t.get("sources", []):
        lbl = src_label(s, pkg, packages)
        if lbl is None:
            continue
        if s.endswith(_HDR_EXTS):
            if public_headers is not None:
                if lbl in public_headers:
                    hdrs.append(lbl)
                else:
                    srcs.append(lbl)
            else:
                hdrs.append(lbl)
        else:
            srcs.append(lbl)
    if rule in ("cc_binary", "cc_test"):
        srcs += hdrs
        hdrs = []
    deps = [
        f'"{canonical_label(d)}"' for d in t.get("deps", []) if "(" not in d
    ]
    if pkg == "runtime/bin/ffi_unit_test" and name.startswith(
            "run_ffi_unit_tests_"):
        deps.append('"//runtime/vm:headers"')
        deps.append('"//runtime/platform:headers"')
        deps.append('"//runtime/include:headers"')
        deps.append('":ffi_cc_includes"')
        data.append('"//runtime/vm:ffi_unit_test_expectations"')
    # Drop TOOLCHAIN_VERSION=/SYSROOT_VERSION= — GN cache-buster defines carrying
    # the clang/sysroot CIPD instance_id (build/config/compiler/BUILD.gn). No
    # source reads them (verified), Bazel invalidates on toolchain change on its
    # own, and the per-box CIPD id made every generated BUILD.bazel diverge across
    # checkouts — the reproducibility killer. Strip so output is toolchain-pin
    # independent.
    is_cross_target = any(suffix in name
                          for suffix in ("_linux_arm", "_linux_arm64",
                                         "_linux_riscv64", "_linux_x64"))

    # Unconditionally strip all architecture and OS defines.
    # Bazel injects them dynamically via //build/config:dart_mode (arch) and
    # rules.bzl wrappers (OS). Hardcoding them in local_defines violates
    # Bazel best practices and is blocked by the pre-commit hook.
    _FORBIDDEN_DEFINES = (
        "TARGET_ARCH_X64",
        "TARGET_ARCH_ARM",
        "TARGET_ARCH_ARM64",
        "TARGET_ARCH_IA32",
        "TARGET_ARCH_RISCV32",
        "TARGET_ARCH_RISCV64",
        "DART_TARGET_OS_LINUX",
        "DART_TARGET_OS_ANDROID",
        "DART_TARGET_OS_MACOS",
        "DART_TARGET_OS_WINDOWS",
        "DART_TARGET_OS_FUCHSIA",
    )
    defines = [
        f'"{d}"' for d in t.get("defines", [])
        if not d.startswith(("TOOLCHAIN_VERSION=", "SYSROOT_VERSION=")) and
        d not in ("NDEBUG", "DEBUG") and d not in _FORBIDDEN_DEFINES
    ]
    include_copts = []
    for inc in t.get("include_dirs", []):
        if inc.startswith(("//out/", "//xcodebuild/")):
            continue  # TODO(M3): generated include dir
        path = inc[2:] if inc.startswith("//") else inc
        path = path.rstrip("/")
        if path:
            include_copts.append(f'"-I{path}"')
    # gn's flag buckets map to Bazel's per-language compile attrs: cflags (both
    # C and C++) -> copts, cflags_c (C only) -> conlyopts, cflags_cc (C++ only)
    # -> cxxopts. Keeping them separate (rather than folding cflags_cc into
    # copts) stops C++-only flags like -std=c++20 / -fno-rtti from landing on .c
    # compiles, and recovers the C-only flags (e.g. -std=c17) the old merge
    # dropped — issue_00001. Drop --sysroot=... (a gn-relative path handled later
    # by a real toolchain feature); filtered out, clang falls back to host headers.
    def _flags(key):
        return [
            f'"{c}"' for c in t.get(key, [])
            if not c.startswith(("--sysroot=", "--target=", "-march=",
                                 "-mtune=")) and
            (c not in ("-m64", "-msse", "-msse2", "-msse3", "-msse4",
                       "-msse4.1", "-msse4.2", "-mavx",
                       "-mavx2") or "zlib_crc32" in name)
        ]

    copts = include_copts + _flags("cflags")
    conlyopts = _flags("cflags_c")
    cxxopts = _flags("cflags_cc")
    linkopts = [f'"-l{l}"' for l in t.get("libs", [])]

    if pkg == "runtime" or pkg.startswith("runtime/"):
        defines = [d for d in defines if d != '"NDEBUG"']
        is_dedicated_product = "_product" in name
        has_product = '"PRODUCT"' in defines or is_dedicated_product
        if '"PRODUCT"' in defines:
            defines = [d for d in defines if d != '"PRODUCT"']
        if is_dedicated_product:
            if '"PRODUCT"' not in defines:
                defines.append('"PRODUCT"')
        dart_mode_dep = '"//build/config:dart_mode_no_arch"' if is_cross_target else '"//build/config:dart_mode"'
        other_dart_mode = '"//build/config:dart_mode"' if is_cross_target else '"//build/config:dart_mode_no_arch"'
        if other_dart_mode in deps:
            deps = [d for d in deps if d != other_dart_mode]
        if dart_mode_dep not in deps:
            deps.append(dart_mode_dep)
        copts = [c for c in copts if c != '"-fno-ident"']

    out = [f'{rule}(\n    name = "{name}",\n']
    if t.get("testonly", False):
        out.append("    testonly = True,\n")
    out.append(_attr_list("srcs", srcs))
    out.append(_attr_list("hdrs", hdrs))
    out.append(_attr_list("deps", deps))
    out.append(_attr_list("local_defines", defines))

    if pkg == "runtime" or pkg.startswith("runtime/"):
        copts_str = _attr_list("copts", copts)
        if copts:
            copts_str = copts_str.rstrip("\n,")
            copts_str += " + select({\n"
            copts_str += "        \"//build/config:debug\": [],\n"
            copts_str += "        \"//conditions:default\": [\"-fno-ident\"],\n"
            copts_str += "    }),\n"
        else:
            copts_str = "    copts = select({\n"
            copts_str += "        \"//build/config:debug\": [],\n"
            copts_str += "        \"//conditions:default\": [\"-fno-ident\"],\n"
            copts_str += "    }),\n"
        out.append(copts_str)
    else:
        out.append(_attr_list("copts", copts))

    out.append(_attr_list("conlyopts", conlyopts))

    if pkg == "runtime" or pkg.startswith("runtime/"):
        cxxopts_str = _attr_list("cxxopts", cxxopts)
        if cxxopts:
            cxxopts_str = cxxopts_str.rstrip("\n,")
            cxxopts_str += " + select({\n"
            cxxopts_str += "        \"//build/config:debug\": [\n"
            cxxopts_str += "            \"-Wno-tautological-undefined-compare\",\n"
            cxxopts_str += "            \"-Wno-undefined-bool-conversion\",\n"
            cxxopts_str += "        ],\n"
            cxxopts_str += "        \"//conditions:default\": [],\n"
            cxxopts_str += "    }),\n"
        else:
            cxxopts_str = "    cxxopts = select({\n"
            cxxopts_str += "        \"//build/config:debug\": [\n"
            cxxopts_str += "            \"-Wno-tautological-undefined-compare\",\n"
            cxxopts_str += "            \"-Wno-undefined-bool-conversion\",\n"
            cxxopts_str += "        ],\n"
            cxxopts_str += "        \"//conditions:default\": [],\n"
            cxxopts_str += "    }),\n"
        out.append(cxxopts_str)
    else:
        out.append(_attr_list("cxxopts", cxxopts))

    out.append(_attr_list("linkopts", linkopts))
    if data:
        out.append(_attr_list("data", data))
    if args:
        out.append(_attr_list("args", args))
    out.append(")\n")
    return "".join(out)


def emit_cc_binary(name, t, pkg, packages):
    if pkg == "runtime/bin/ffi_unit_test" and name == "run_ffi_unit_tests_x64_linux":
        return emit_cc_library(name,
                               t,
                               pkg,
                               packages,
                               rule="cc_test",
                               args=['"--all"'])
    return emit_cc_library(name, t, pkg, packages, rule="cc_binary")


def emit_group(name, t, pkg, packages):
    """gn group -> cc_library with deps only.

    A gn group is a named bundle of dependencies (no sources). The closest
    Bazel primitive that propagates cc deps is a cc_library with no srcs.
    """
    deps = [
        f'"{canonical_label(d)}"' for d in t.get("deps", []) if "(" not in d
    ]
    out = [f'cc_library(\n    name = "{name}",\n']
    if t.get("testonly", False):
        out.append("    testonly = True,\n")
    out.append(_attr_list("deps", deps))
    out.append(")\n")
    return "".join(out)


def emit_stub(rule_kind):
    """Empty cc_library stub keeps the label resolvable at analysis time."""

    def _emit(name, t, pkg, packages):
        return (
            f'# TODO(M3): {rule_kind} for {name} (gn type={t.get("type")})\n'
            f'cc_library(name = "{name}")\n')

    return _emit


EMITTERS = {
    "source_set": emit_cc_library,
    "static_library": emit_cc_library,
    "shared_library": emit_stub("cc_shared_library"),
    "executable": emit_cc_binary,
    "action": emit_stub("genrule"),
    "action_foreach": emit_stub("genrule"),
    "copy": emit_stub("copy"),
    "group": emit_group,
    "generated_file": emit_stub("genrule"),
}


def _emit_targets_body(targets, pkg, packages):
    """Per-target rule text for a BUILD body: each known target followed by a
    blank line; unknown types -> a lone TODO comment. Shared by the BUILD.bazel
    writer and the §7 gen_targets.bzl macro writer so both emit identically."""
    parts = []
    for name, t in sorted(targets):
        t_type = t.get("type")
        emit = EMITTERS.get(t_type)
        if emit is None:
            parts.append(f'# TODO(M3): unknown gn type {t_type} for {name}\n')
            continue
        parts.append(emit(name, t, pkg, packages))
        parts.append("\n")
    return "".join(parts)


def _owned_target_names(build_path):
    """Names of targets already defined in a hand-authored BUILD.bazel. The §7
    macro skips these (the hand file owns them). Empty if the file is absent.

    The `name = "..."` match tolerates formatting shifts — single or double
    quotes and any spacing around `=` — and `\\b` anchors `name` to a word
    boundary so it does not match other attributes ending in "name" (filename,
    pathname, …)."""
    if not os.path.exists(build_path):
        return set()
    names = set()
    with open(build_path) as f:
        for line in f:
            clean_line = line.split('#')[0]
            m = re.search(r"""\bname\s*=\s*["']([^"']+)["']""", clean_line)
            if m:
                names.add(m.group(1))
    return names


# Rules/attributes the translator NEVER emits, so their presence in an existing
# BUILD.bazel proves a human hand-authored it (dart snapshot rules, real
# genrules, shared-object cc_binary, cc_shared_library). The TODO stubs emit the
# bare words "genrule"/"cc_shared_library" in a comment but never followed by
# "(", so the open-paren anchors keep this from matching pure-machine output.
_HAND_AUTHORED_MARKERS = re.compile(
    r'load\("//tools/bazel/dart|genrule\(|linkshared|cc_shared_library\(')


def _is_hand_authored_overlay(build_path):
    """True if an existing BUILD.bazel carries hand-authored rules a regen must
    not clobber. Belt-and-suspenders alongside the explicit skip set below: a
    new overlay is protected the moment it gains hand rules, so nobody has to
    remember to add it here (the omission that reverted the utils/* snapshots)."""
    if not os.path.exists(build_path):
        return False
    with open(build_path) as f:
        lines_clean = []
        for line in f:
            lines_clean.append(line.split('#')[0])
        content = '\n'.join(lines_clean)
        return bool(_HAND_AUTHORED_MARKERS.search(content))


def write_gen_targets_bzl(root, pkg, targets, packages):
    """§7 overlay: write <pkg>/gen_targets.bzl (a gen_targets() macro) with the
    package's MACHINE targets, and NEVER touch BUILD.bazel. A target is machine-
    owned iff it is not defined in the hand-authored BUILD.bazel and not in
    GEN_TARGETS_DROP. Indented one level so it sits inside `def gen_targets()`."""
    owned = _owned_target_names(os.path.join(root, pkg, "BUILD.bazel"))
    drop = GEN_TARGETS_DROP.get(pkg, set())
    machine = [(n, t) for n, t in targets if n not in owned and n not in drop]
    body = (_emit_targets_body(machine, pkg, packages) or
            "pass\n").rstrip() + "\n"
    out_path = os.path.join(root, pkg, "gen_targets.bzl")
    rules_used = get_rules_used(machine, pkg)
    load_stmt = make_load_statement(rules_used)
    with open(out_path, "w") as f:
        f.write(GEN_TARGETS_DOCSTRING)
        f.write("\n\n")
        if load_stmt:
            f.write(load_stmt)
        f.write("def gen_targets():\n")
        f.write(
            '    """Declare this package\'s machine-derived cc_* targets (see header).\n\n'
        )
        f.write(
            '    Called from the hand-authored BUILD.bazel, which owns every hand-fixed\n'
        )
        f.write(
            '    target; targets defined there are excluded from this macro by the translator.\n'
        )
        f.write('    """\n\n')
        f.write(textwrap.indent(body, "    "))
    n_drop = sum(1 for n, _ in targets if n in drop)
    n_hand = len(targets) - len(machine) - n_drop
    print(
        f"wrote {out_path} (gen_targets() macro: {len(machine)} machine targets; "
        f"{n_hand} hand-owned in BUILD.bazel, {n_drop} obsolete dropped)",
        file=sys.stderr)


def _propagate_testonly(desc):
    # Force testonly = True for the target we turned into cc_test.
    # Bazel implicitly treats cc_test as testonly, so any target depending on it
    # must also be marked testonly.
    # Handle potential toolchain suffixes (e.g. target_test + "(...)") robustly.
    target_test = "//runtime/bin/ffi_unit_test:run_ffi_unit_tests_x64_linux"
    for label in desc:
        if label == target_test or label.startswith(target_test + "("):
            desc[label]["testonly"] = True

    # Build a reverse dependency map (child -> parents)
    rev_deps = {}
    for label, t in desc.items():
        for dep in t.get("deps", []):
            rev_deps.setdefault(dep, []).append(label)

    # Initialize queue with all targets currently marked testonly
    queue = [label for label, t in desc.items() if t.get("testonly", False)]
    visited = set(queue)

    # BFS to propagate testonly transitively to all ancestors using an index pointer
    # to achieve a true linear O(N) complexity (avoiding O(N^2) list.pop(0) shifts).
    idx = 0
    while idx < len(queue):
        curr = queue[idx]
        idx += 1
        if curr in desc:
            desc[curr]["testonly"] = True
        for parent in rev_deps.get(curr, []):
            if parent not in visited:
                visited.add(parent)
                queue.append(parent)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("desc_json", help="gn desc //* --format=json output")
    ap.add_argument("--root",
                    default=".",
                    help="Repo root for BUILD.bazel output")
    args = ap.parse_args()

    global _ROOT
    _ROOT = args.root

    with open(args.desc_json) as f:
        desc = json.load(f)

    _propagate_testonly(desc)

    # Skip non-default-toolchain entries — gn desc represents them as
    # //path:name(//toolchain:tc), which is illegal in Bazel target names.
    # Multi-toolchain folding is M4 (select() blocks).
    by_pkg = defaultdict(list)
    for label, target in desc.items():
        if "(" in label:
            continue
        pkg, name = split_label(label)
        by_pkg[pkg].append((name, target))

    # Pre-existing BUILD.bazel files (e.g., upstream third_party Bazel
    # builds) anchor their directories as Bazel packages. Walk the tree
    # to seed the package set so src_label routes cross-pkg refs right;
    # never overwrite a file we didn't write ourselves.
    existing_packages = set()
    foreign_packages = set()
    for root, _, files in os.walk(args.root):
        if "BUILD.bazel" not in files:
            continue
        rel = os.path.relpath(root, args.root)
        if rel == ".":
            continue
        existing_packages.add(rel)
        # §7 packages have a HAND-AUTHORED BUILD.bazel (no generated marker) by
        # design — it's ours, not foreign. Skip the marker test so the package
        # is not treated as foreign (which would also skip its child packages).
        if rel in GEN_TARGETS_PACKAGES:
            continue
        with open(os.path.join(root, "BUILD.bazel")) as f:
            if _GENERATED_MARKER not in f.read(256):
                foreign_packages.add(rel)

    packages = set(by_pkg.keys()) | existing_packages

    def _has_foreign_ancestor(p):
        cur = os.path.dirname(p)
        while cur:
            if cur in foreign_packages:
                return True
            cur = os.path.dirname(cur)
        return False

    for pkg, targets in sorted(by_pkg.items()):
        if pkg in {
                "",
                "runtime",
                "runtime/platform",
                "sdk",
                "runtime/include",
                "third_party/boringssl",
                "third_party/icu",
                "third_party/zlib",
                "samples/embedder",
                "third_party/binaryen",
                "utils/bazel",
        }:
            print(f"skipping {pkg} (hand-authored BUILD.bazel overlay)",
                  file=sys.stderr)
            continue
        if pkg in GEN_TARGETS_PACKAGES:
            # §7 overlay: emit gen_targets.bzl; the hand-authored BUILD.bazel is
            # never written here (so a regen can't clobber its hand-fixes).
            write_gen_targets_bzl(args.root, pkg, targets, packages)
            continue
        if pkg in foreign_packages:
            print(f"skipping {pkg} (upstream BUILD.bazel)", file=sys.stderr)
            continue
        if _has_foreign_ancestor(pkg):
            print(f"skipping {pkg} (foreign ancestor)", file=sys.stderr)
            continue
        out_path = os.path.join(args.root, pkg, "BUILD.bazel")
        if _is_hand_authored_overlay(out_path):
            print(f"skipping {pkg} (hand-authored overlay detected)",
                  file=sys.stderr)
            continue
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        rules_used = get_rules_used(targets, pkg)
        load_stmt = make_load_statement(rules_used)
        with open(out_path, "w") as f:
            f.write(HEADER_PREFIX)
            if load_stmt:
                f.write(load_stmt)
            f.write(HEADER_SUFFIX)
            f.write(_emit_targets_body(targets, pkg, packages).rstrip() + "\n")
            if pkg == "runtime/bin/ffi_unit_test":
                f.write(FFI_CC_INCLUDES_TARGET)
        print(f"wrote {out_path} ({len(targets)} targets)", file=sys.stderr)


if __name__ == "__main__":
    main()
