#!/usr/bin/env python3
"""Translate `gn desc <out_dir> //* --format=json` to BUILD.bazel files.

M2 skeleton (DESIGN.md §4.1). Groups targets by source BUILD.gn directory
and emits one BUILD.bazel per directory. Handles the six common GN target
types structurally; gaps surfaced by M3 (`bazel build //runtime/vm:libdart_vm_jit`)
get hand-fixed in the generated files.

Usage:
  tools/bazel/translate_gn_desc.py gn-desc.json --root .
"""

import argparse
import json
import os
import sys
from collections import defaultdict

_GENERATED_MARKER = "AUTO-GENERATED by tools/bazel/translate_gn_desc.py"

HEADER = f"""# {_GENERATED_MARKER} from `gn desc` output.
# Hand-fixes belong in this file (M3); rerun the translator to refresh structural
# bits and re-apply fixes from version control.

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_shared_library")

package(default_visibility = ["//visibility:public"])

# GN lets one target's sources reach into other BUILD.gn dirs; Bazel
# requires cross-package file refs to be explicitly exported. Bulk-export
# every file in the package so the gn-shaped source lists keep working.
exports_files(glob(
    ["**/*.h", "**/*.hpp", "**/*.hh", "**/*.inc",
     "**/*.cc", "**/*.cpp", "**/*.c", "**/*.S", "**/*.s"],
    allow_empty = True,
))

"""


def split_label(label):
    """`//foo/bar:baz` -> (`foo/bar`, `baz`).  `//foo/bar` -> (`foo/bar`, `bar`)."""
    assert label.startswith("//"), label
    body = label[2:]
    if ":" in body:
        path, name = body.split(":", 1)
    else:
        path = body
        name = os.path.basename(body) or body
    return path, name


_ROOT = "."  # set by main(); used by src_label for on-disk existence check


def src_label(src_path, pkg, packages):
    """gn workspace path `//pkg/sub/foo.cc` -> Bazel src reference.

    Walks up `src_path`'s directory chain looking for the longest known
    Bazel package (any dir that has GN targets and so will get a
    BUILD.bazel). That package owns the file; emit either a relative path
    (when owning pkg == current pkg) or an absolute cross-package label.
    Returns None when the file is a generated output (under //out/...) or
    missing from disk — caller drops it (codegen action wiring is M5).
    """
    if src_path.startswith("//out/"):
        return None
    assert src_path.startswith("//"), src_path
    rel = src_path[2:]
    if not os.path.exists(os.path.join(_ROOT, rel)):
        return None
    cur = os.path.dirname(rel)
    owning_pkg = ""
    while cur:
        if cur in packages:
            owning_pkg = cur
            break
        cur = os.path.dirname(cur)
    inner = rel[len(owning_pkg) + 1:] if owning_pkg else rel
    if owning_pkg == pkg:
        return f'"{inner}"'
    return f'"//{owning_pkg}:{inner}"'


def _attr_list(name, items, indent=4):
    if not items:
        return ""
    pad = " " * indent
    body = "\n".join(f"{pad}    {x}," for x in items)
    return f"{pad}{name} = [\n{body}\n{pad}],\n"


_HDR_EXTS = (".h", ".hpp", ".hh", ".inc")


def emit_cc_library(name, t, pkg, packages):
    """source_set / static_library -> cc_library."""
    hdrs, srcs = [], []
    for s in t.get("sources", []):
        lbl = src_label(s, pkg, packages)
        if lbl is None:
            continue
        (hdrs if s.endswith(_HDR_EXTS) else srcs).append(lbl)
    deps = [f'"{d}"' for d in t.get("deps", [])]
    defines = [f'"{d}"' for d in t.get("defines", [])]
    include_copts = []
    for inc in t.get("include_dirs", []):
        if inc.startswith("//out/"):
            continue  # TODO(M3): generated include dir
        path = inc[2:] if inc.startswith("//") else inc
        path = path.rstrip("/")
        if path:
            include_copts.append(f'"-I{path}"')
    # Drop flags whose values are gn-relative paths we don't reproduce in
    # Bazel yet — most prominently --sysroot=../../buildtools/sysroot/linux
    # (handled later by a real toolchain feature). With it filtered, clang
    # falls back to the host's system headers, which is fine for M3.
    raw_flags = list(t.get("cflags", [])) + list(t.get("cflags_cc", []))
    raw_flags = [f for f in raw_flags if not f.startswith("--sysroot=")]
    copts = include_copts + [f'"{c}"' for c in raw_flags]
    linkopts = [f'"-l{l}"' for l in t.get("libs", [])]
    out = [f'cc_library(\n    name = "{name}",\n']
    out.append(_attr_list("srcs", srcs))
    out.append(_attr_list("hdrs", hdrs))
    out.append(_attr_list("deps", deps))
    out.append(_attr_list("defines", defines))
    out.append(_attr_list("copts", copts))
    out.append(_attr_list("linkopts", linkopts))
    out.append(")\n")
    return "".join(out)


def emit_cc_binary(name, t, pkg, packages):
    body = emit_cc_library(name, t, pkg, packages).replace("cc_library(", "cc_binary(", 1)
    return body


def emit_group(name, t, pkg, packages):
    """gn group -> cc_library with deps only.

    A gn group is a named bundle of dependencies (no sources). The closest
    Bazel primitive that propagates cc deps is a cc_library with no srcs.
    """
    deps = [f'"{d}"' for d in t.get("deps", [])]
    out = [f'cc_library(\n    name = "{name}",\n']
    out.append(_attr_list("deps", deps))
    out.append(")\n")
    return "".join(out)


def emit_stub(rule_kind):
    """Empty cc_library stub keeps the label resolvable at analysis time."""
    def _emit(name, t, pkg, packages):
        return (
            f'# TODO(M3): {rule_kind} for {name} (gn type={t["type"]})\n'
            f'cc_library(name = "{name}")\n'
        )
    return _emit


EMITTERS = {
    "source_set":     emit_cc_library,
    "static_library": emit_cc_library,
    "shared_library": emit_stub("cc_shared_library"),
    "executable":     emit_cc_binary,
    "action":         emit_stub("genrule"),
    "action_foreach": emit_stub("genrule"),
    "copy":           emit_stub("copy"),
    "group":          emit_group,
    "generated_file": emit_stub("genrule"),
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("desc_json", help="gn desc //* --format=json output")
    ap.add_argument("--root", default=".", help="Repo root for BUILD.bazel output")
    args = ap.parse_args()

    global _ROOT
    _ROOT = args.root

    with open(args.desc_json) as f:
        desc = json.load(f)

    # Skip non-default-toolchain entries — gn desc represents them as
    # //path:name(//toolchain:tc), which is illegal in Bazel target names.
    # Multi-toolchain folding is M4 (select() blocks).
    by_pkg = defaultdict(list)
    for label, target in desc.items():
        if "(" in label:
            continue
        pkg, name = split_label(label)
        by_pkg[pkg].append((name, target))

    # Pre-existing BUILD.bazel files (e.g., upstream third_party Bazel
    # builds) anchor their directories as Bazel packages. Walk the tree
    # to seed the package set so src_label routes cross-pkg refs right;
    # never overwrite a file we didn't write ourselves.
    existing_packages = set()
    foreign_packages = set()
    for root, _, files in os.walk(args.root):
        if "BUILD.bazel" not in files:
            continue
        rel = os.path.relpath(root, args.root)
        if rel == ".":
            continue
        existing_packages.add(rel)
        with open(os.path.join(root, "BUILD.bazel")) as f:
            if _GENERATED_MARKER not in f.read(256):
                foreign_packages.add(rel)

    packages = set(by_pkg.keys()) | existing_packages

    def _has_foreign_ancestor(p):
        cur = os.path.dirname(p)
        while cur:
            if cur in foreign_packages:
                return True
            cur = os.path.dirname(cur)
        return False

    for pkg, targets in sorted(by_pkg.items()):
        if pkg in foreign_packages:
            print(f"skipping {pkg} (upstream BUILD.bazel)", file=sys.stderr)
            continue
        if _has_foreign_ancestor(pkg):
            print(f"skipping {pkg} (foreign ancestor)", file=sys.stderr)
            continue
        out_path = os.path.join(args.root, pkg, "BUILD.bazel")
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w") as f:
            f.write(HEADER)
            for name, t in sorted(targets):
                emit = EMITTERS.get(t["type"])
                if emit is None:
                    f.write(f'# TODO(M3): unknown gn type {t["type"]} for {name}\n')
                    continue
                f.write(emit(name, t, pkg, packages))
                f.write("\n")
        print(f"wrote {out_path} ({len(targets)} targets)", file=sys.stderr)


if __name__ == "__main__":
    main()
