"""AUTO-GENERATED by tools/bazel/translate_gn_desc.py from `gn desc` output.

§7 overlay (docs/todo_issues/m4_multiconfig_scoping.md §7): the machine-derived
cc_* targets for this package. A regen overwrites THIS file freely; it never
touches the HAND-AUTHORED BUILD.bazel that load()s + calls gen_targets() and
owns the hand-fixed targets. Mirrors tools/bazel/dart/packages.bzl. DO NOT EDIT.
"""

def gen_targets():
    """Declare this package's machine-derived cc_* targets (see header).

    Called from the hand-authored BUILD.bazel, which owns every hand-fixed
    target; targets defined there are excluded from this macro by the translator.
    """

    pass
