#!/usr/bin/env python3
# Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

"""Generate tools/bazel/dart/packages.bzl — the per-package dart_library graph.

rules_dart Step 3 (docs/todo_issues/rules_dart_scoping.md §6 #3, §8). Replaces
the opaque //:dart_package_sources blob with one dart_library per package so a
tool snapshot depends only on its own transitive closure, recovering Bazel
incrementality.

Data sources (both already maintained by the SDK):
  * .dart_tool/package_config.json — package name -> root dir (197 entries, all
    local). Generated by tools/generate_package_config.py.
  * <pkg>/pubspec.yaml `dependencies:` — the dep edges. Empirically a cycle-free
    safe superset of each package's real `package:` imports; dev_dependencies are
    EXCLUDED (they introduce analyzer<->test cycles, which Bazel forbids, and are
    not needed for the import closure).

All dart_library targets are declared in the ROOT Bazel package: pkg/,
third_party/pkg/, third_party/devtools have no sub-BUILD.bazel, so they belong to
//  and are globbable from the root. This keeps the graph out of the DEPS-pinned
subrepo dirs (out-of-band friendly).

Run from the SDK checkout root:
    python3 tools/bazel/dart/gen_packages.py
Re-run whenever a pubspec's `dependencies:` change or packages are added/removed
(i.e. alongside tools/generate_package_config.py).
"""

import json
import os
import re
import sys

_HEADER = '''\
# GENERATED by tools/bazel/dart/gen_packages.py — DO NOT EDIT BY HAND.
# Re-run `python3 tools/bazel/dart/gen_packages.py` from the SDK root to refresh.
#
# rules_dart Step 3: one dart_library per package (name -> transitive .dart
# closure), keyed off .dart_tool/package_config.json + each pubspec's
# `dependencies:`. See docs/todo_issues/rules_dart_scoping.md §8.

load("//tools/bazel/dart:defs.bzl", "dart_library")

def dart_packages():
    """Declare a dart_library for every package in package_config.json.

    Targets are named dart_pkg_<package> (so //:dart_pkg_dtd_impl) to share the
    root package's namespace with the hand-maintained cc_library group targets
    (//:analysis_server etc.) and the tools/utils workspace packages without
    colliding.
    """
'''

# Prefix for every generated target: the dart_library graph lives in the ROOT
# package (only it can glob pkg/ + third_party/pkg/), so names must not collide
# with hand-maintained root targets or workspace package names.
_PREFIX = "dart_pkg_"


def parse_dependencies(pubspec_path):
    """Return the set of names under the top-level `dependencies:` key.

    Hand-parsed (no PyYAML dep): a top-level key starts at column 0; a direct
    dependency is indented exactly two spaces under `dependencies:`. We ignore
    dev_dependencies, dependency_overrides, environment, etc.
    """
    deps = set()
    section = None
    with open(pubspec_path, encoding="utf-8") as f:
        for line in f:
            if re.match(r"^[A-Za-z_]", line):
                key = line.split(":", 1)[0].strip()
                section = key if key == "dependencies" else None
                continue
            if section == "dependencies":
                m = re.match(r"^  ([A-Za-z0-9_]+):", line)
                if m:
                    deps.add(m.group(1))
    return deps


def main():
    root = os.getcwd()
    cfg_path = os.path.join(root, ".dart_tool", "package_config.json")
    if not os.path.exists(cfg_path):
        sys.exit("error: %s not found — run from the SDK checkout root "
                 "(and after tools/generate_package_config.py)." % cfg_path)
    cfg = json.load(open(cfg_path))
    base = os.path.join(root, ".dart_tool")

    # name -> (repo-root-relative pkg dir, packageUri lib subdir)
    pkgs = {}
    for p in cfg["packages"]:
        absdir = os.path.normpath(os.path.join(base, p["rootUri"]))
        reldir = os.path.relpath(absdir, root)
        if reldir.startswith(".."):
            # Outside the checkout — can't glob from the root package. Skip.
            sys.stderr.write("skip (outside checkout): %s -> %s\n"
                             % (p["name"], reldir))
            continue
        if reldir == ".":
            # The pub workspace-root sentinel (pubspec `name: _`): no lib/, not an
            # importable package. Skip it.
            continue
        lib = (p.get("packageUri") or "lib/").rstrip("/")
        pkgs[p["name"]] = (reldir, lib)

    known = set(pkgs)
    lines = [_HEADER]
    for name in sorted(pkgs):
        reldir, lib = pkgs[name]
        pubspec = os.path.join(root, reldir, "pubspec.yaml")
        deps = set()
        if os.path.exists(pubspec):
            deps = {d for d in parse_dependencies(pubspec) if d in known} - {name}
        glob_path = "%s/%s/**/*.dart" % (reldir, lib)
        dep_labels = ", ".join('":%s%s"' % (_PREFIX, d) for d in sorted(deps))
        lines.append('    dart_library(')
        lines.append('        name = "%s%s",' % (_PREFIX, name))
        lines.append('        srcs = native.glob(["%s"], allow_empty = True),'
                     % glob_path)
        lines.append('        deps = [%s],' % dep_labels)
        lines.append('    )')

    out = os.path.join(root, "tools", "bazel", "dart", "packages.bzl")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s — %d dart_library targets" % (out, len(pkgs)))


if __name__ == "__main__":
    main()
