# GENERATED by tools/bazel/dart/gen_packages.py — DO NOT EDIT BY HAND.
# Re-run `python3 tools/bazel/dart/gen_packages.py` from the SDK root to refresh.
#
# rules_dart Step 3: one dart_library per package (name -> transitive .dart
# closure), keyed off .dart_tool/package_config.json + each pubspec's
# `dependencies:`. See docs/todo_issues/rules_dart_scoping.md §8.

load("//tools/bazel/dart:defs.bzl", "dart_library")

def dart_packages():
    """Declare a dart_library for every package in package_config.json.

    Targets are named dart_pkg_<package> (so //:dart_pkg_dtd_impl) to share the
    root package's namespace with the hand-maintained cc_library group targets
    (//:analysis_server etc.) and the tools/utils workspace packages without
    colliding.
    """

    dart_library(
        name = "dart_pkg__fe_analyzer_shared",
        srcs = native.glob(["pkg/_fe_analyzer_shared/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg__js_interop_checks",
        srcs = native.glob(["pkg/_js_interop_checks/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg_front_end", ":dart_pkg_kernel"],
    )
    dart_library(
        name = "dart_pkg_analysis_server",
        srcs = native.glob(["pkg/analysis_server/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg_analysis_server_plugin", ":dart_pkg_analyzer", ":dart_pkg_analyzer_plugin", ":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_convert", ":dart_pkg_crypto", ":dart_pkg_dart_style", ":dart_pkg_dtd", ":dart_pkg_http", ":dart_pkg_json_rpc_2", ":dart_pkg_language_server_protocol", ":dart_pkg_linter", ":dart_pkg_memory_usage", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_perf_witness", ":dart_pkg_platform", ":dart_pkg_pub_semver", ":dart_pkg_stream_channel", ":dart_pkg_telemetry", ":dart_pkg_unified_analytics", ":dart_pkg_vm_service", ":dart_pkg_watcher", ":dart_pkg_yaml", ":dart_pkg_yaml_edit"],
    )
    dart_library(
        name = "dart_pkg_analysis_server_client",
        srcs = native.glob(["pkg/analysis_server_client/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_path", ":dart_pkg_pub_semver"],
    )
    dart_library(
        name = "dart_pkg_analysis_server_plugin",
        srcs = native.glob(["pkg/analysis_server_plugin/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_analyzer_plugin", ":dart_pkg_collection", ":dart_pkg_meta", ":dart_pkg_yaml", ":dart_pkg_yaml_edit"],
    )
    dart_library(
        name = "dart_pkg_analyzer",
        srcs = native.glob(["pkg/analyzer/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg_collection", ":dart_pkg_convert", ":dart_pkg_crypto", ":dart_pkg_glob", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_source_span", ":dart_pkg_watcher", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_analyzer_cli",
        srcs = native.glob(["pkg/analyzer_cli/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_linter", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_analyzer_plugin",
        srcs = native.glob(["pkg/analyzer_plugin/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_collection", ":dart_pkg_dart_style", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_analyzer_testing",
        srcs = native.glob(["pkg/analyzer_testing/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_analyzer_utilities",
        srcs = native.glob(["pkg/analyzer_utilities/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_analyzer_testing", ":dart_pkg_api_summary", ":dart_pkg_collection", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_source_span", ":dart_pkg_test", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_api_summary",
        srcs = native.glob(["pkg/api_summary/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_path", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_args",
        srcs = native.glob(["third_party/pkg/core/pkgs/args/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_async",
        srcs = native.glob(["third_party/pkg/core/pkgs/async/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_async_helper",
        srcs = native.glob(["pkg/async_helper/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_expect"],
    )
    dart_library(
        name = "dart_pkg_bazel_worker",
        srcs = native.glob(["third_party/pkg/tools/pkgs/bazel_worker/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_protobuf"],
    )
    dart_library(
        name = "dart_pkg_benchmark_harness",
        srcs = native.glob(["third_party/pkg/tools/pkgs/benchmark_harness/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args"],
    )
    dart_library(
        name = "dart_pkg_bisect_dart",
        srcs = native.glob(["pkg/bisect_dart/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_cli_config", ":dart_pkg_logging"],
    )
    dart_library(
        name = "dart_pkg_boolean_selector",
        srcs = native.glob(["third_party/pkg/tools/pkgs/boolean_selector/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_source_span", ":dart_pkg_string_scanner"],
    )
    dart_library(
        name = "dart_pkg_browser_launcher",
        srcs = native.glob(["third_party/pkg/tools/pkgs/browser_launcher/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_logging", ":dart_pkg_path", ":dart_pkg_webkit_inspection_protocol"],
    )
    dart_library(
        name = "dart_pkg_build_integration",
        srcs = native.glob(["pkg/build_integration/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_front_end"],
    )
    dart_library(
        name = "dart_pkg_cfg",
        srcs = native.glob(["pkg/cfg/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_kernel", ":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_characters",
        srcs = native.glob(["third_party/pkg/core/pkgs/characters/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_checks",
        srcs = native.glob(["third_party/pkg/test/pkgs/checks/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_meta", ":dart_pkg_test_api"],
    )
    dart_library(
        name = "dart_pkg_cli_config",
        srcs = native.glob(["third_party/pkg/tools/pkgs/cli_config/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_cli_util",
        srcs = native.glob(["third_party/pkg/tools/pkgs/cli_util/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_ffi", ":dart_pkg_meta", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_clock",
        srcs = native.glob(["third_party/pkg/tools/pkgs/clock/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_code_assets",
        srcs = native.glob(["third_party/pkg/native/pkgs/code_assets/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_hooks"],
    )
    dart_library(
        name = "dart_pkg_collection",
        srcs = native.glob(["third_party/pkg/core/pkgs/collection/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_compiler",
        srcs = native.glob(["pkg/compiler/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg__js_interop_checks", ":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_dart2js_info", ":dart_pkg_front_end", ":dart_pkg_js_ast", ":dart_pkg_js_runtime", ":dart_pkg_js_shared", ":dart_pkg_kernel", ":dart_pkg_meta", ":dart_pkg_mmap", ":dart_pkg_record_use", ":dart_pkg_shell_arg_splitter", ":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_convert",
        srcs = native.glob(["third_party/pkg/core/pkgs/convert/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_typed_data"],
    )
    dart_library(
        name = "dart_pkg_corpus",
        srcs = native.glob(["third_party/pkg/ecosystem/pkgs/corpus/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_cli_util", ":dart_pkg_collection", ":dart_pkg_http", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_coverage",
        srcs = native.glob(["third_party/pkg/tools/pkgs/coverage/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_cli_config", ":dart_pkg_glob", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_source_maps", ":dart_pkg_stack_trace", ":dart_pkg_vm_service", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_crypto",
        srcs = native.glob(["third_party/pkg/core/pkgs/crypto/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_csslib",
        srcs = native.glob(["third_party/pkg/tools/pkgs/csslib/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_source_span"],
    )
    dart_library(
        name = "dart_pkg_dap",
        srcs = native.glob(["third_party/pkg/dap/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_dart2bytecode",
        srcs = native.glob(["pkg/dart2bytecode/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_front_end", ":dart_pkg_kernel", ":dart_pkg_vm"],
    )
    dart_library(
        name = "dart_pkg_dart2js_info",
        srcs = native.glob(["pkg/dart2js_info/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_fixnum", ":dart_pkg_path", ":dart_pkg_protobuf", ":dart_pkg_shelf", ":dart_pkg_vm_snapshot_analysis", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_dart2js_runtime_metrics",
        srcs = native.glob(["pkg/dart2js_runtime_metrics/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_dart2js_tools",
        srcs = native.glob(["pkg/dart2js_tools/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_path", ":dart_pkg_source_maps", ":dart_pkg_source_span", ":dart_pkg_stack_trace"],
    )
    dart_library(
        name = "dart_pkg_dart2native",
        srcs = native.glob(["pkg/dart2native/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_code_assets", ":dart_pkg_collection", ":dart_pkg_front_end", ":dart_pkg_kernel", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_dart2wasm",
        srcs = native.glob(["pkg/dart2wasm/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg__js_interop_checks", ":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_build_integration", ":dart_pkg_collection", ":dart_pkg_compiler", ":dart_pkg_front_end", ":dart_pkg_kernel", ":dart_pkg_linter", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_record_use", ":dart_pkg_vm", ":dart_pkg_wasm_builder"],
    )
    dart_library(
        name = "dart_pkg_dart_data_home",
        srcs = native.glob(["pkg/dart_data_home/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_cli_util", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_dart_flutter_team_lints",
        srcs = native.glob(["third_party/pkg/ecosystem/pkgs/dart_flutter_team_lints/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_lints"],
    )
    dart_library(
        name = "dart_pkg_dart_internal",
        srcs = native.glob(["pkg/dart_internal/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_dart_mcp",
        srcs = native.glob(["third_party/pkg/ai/pkgs/dart_mcp/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_collection", ":dart_pkg_json_rpc_2", ":dart_pkg_meta", ":dart_pkg_stream_channel", ":dart_pkg_stream_transform"],
    )
    dart_library(
        name = "dart_pkg_dart_mcp_server",
        srcs = native.glob(["third_party/pkg/ai/pkgs/dart_mcp_server/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_async", ":dart_pkg_cli_util", ":dart_pkg_collection", ":dart_pkg_dart_mcp", ":dart_pkg_dds_service_extensions", ":dart_pkg_devtools_shared", ":dart_pkg_dtd", ":dart_pkg_file", ":dart_pkg_http", ":dart_pkg_json_rpc_2", ":dart_pkg_language_server_protocol", ":dart_pkg_meta", ":dart_pkg_mime", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_process", ":dart_pkg_stream_channel", ":dart_pkg_unified_analytics", ":dart_pkg_vm_service", ":dart_pkg_watcher", ":dart_pkg_web_socket", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_dart_runtime_service",
        srcs = native.glob(["pkg/dart_runtime_service/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_dds", ":dart_pkg_dds_service_extensions", ":dart_pkg_json_rpc_2", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_pool", ":dart_pkg_shelf", ":dart_pkg_shelf_web_socket", ":dart_pkg_sse", ":dart_pkg_stream_channel", ":dart_pkg_vm_service", ":dart_pkg_web_socket_channel"],
    )
    dart_library(
        name = "dart_pkg_dart_runtime_service_vm",
        srcs = native.glob(["pkg/dart_runtime_service_vm/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_dart_runtime_service", ":dart_pkg_file", ":dart_pkg_frontend_server", ":dart_pkg_json_rpc_2", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_stream_channel", ":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_dart_service_protocol_shared",
        srcs = native.glob(["pkg/dart_service_protocol_shared/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_dart_style",
        srcs = native.glob(["third_party/pkg/dart_style/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_source_span", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_dartdev",
        srcs = native.glob(["pkg/dartdev/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analysis_server", ":dart_pkg_analysis_server_client", ":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_cli_util", ":dart_pkg_code_assets", ":dart_pkg_collection", ":dart_pkg_dart2native", ":dart_pkg_dart_data_home", ":dart_pkg_dart_mcp_server", ":dart_pkg_dart_style", ":dart_pkg_dartdoc", ":dart_pkg_data_assets", ":dart_pkg_dds", ":dart_pkg_dds_service_extensions", ":dart_pkg_dtd_impl", ":dart_pkg_file", ":dart_pkg_front_end", ":dart_pkg_frontend_server", ":dart_pkg_hooks", ":dart_pkg_hooks_runner", ":dart_pkg_http", ":dart_pkg_kernel", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_perf_witness", ":dart_pkg_pub", ":dart_pkg_pub_formats", ":dart_pkg_unified_analytics", ":dart_pkg_vm", ":dart_pkg_vm_service", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_dartdoc",
        srcs = native.glob(["third_party/pkg/dartdoc/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_glob", ":dart_pkg_html", ":dart_pkg_logging", ":dart_pkg_markdown", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_source_span", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_data_assets",
        srcs = native.glob(["third_party/pkg/native/pkgs/data_assets/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_hooks"],
    )
    dart_library(
        name = "dart_pkg_dds",
        srcs = native.glob(["pkg/dds/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_async", ":dart_pkg_browser_launcher", ":dart_pkg_collection", ":dart_pkg_dap", ":dart_pkg_dds_service_extensions", ":dart_pkg_devtools_shared", ":dart_pkg_dtd", ":dart_pkg_extension_discovery", ":dart_pkg_http_multi_server", ":dart_pkg_json_rpc_2", ":dart_pkg_meta", ":dart_pkg_mime", ":dart_pkg_path", ":dart_pkg_shelf", ":dart_pkg_shelf_proxy", ":dart_pkg_shelf_static", ":dart_pkg_shelf_web_socket", ":dart_pkg_sse", ":dart_pkg_stream_channel", ":dart_pkg_vm_service", ":dart_pkg_web_socket_channel"],
    )
    dart_library(
        name = "dart_pkg_dds_service_extensions",
        srcs = native.glob(["pkg/dds_service_extensions/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_dap", ":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_dev_compiler",
        srcs = native.glob(["pkg/dev_compiler/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg__js_interop_checks", ":dart_pkg_args", ":dart_pkg_async", ":dart_pkg_bazel_worker", ":dart_pkg_build_integration", ":dart_pkg_collection", ":dart_pkg_front_end", ":dart_pkg_js_shared", ":dart_pkg_kernel", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_shell_arg_splitter", ":dart_pkg_source_maps", ":dart_pkg_source_span"],
    )
    dart_library(
        name = "dart_pkg_devtools_shared",
        srcs = native.glob(["third_party/devtools/devtools_shared/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_dtd", ":dart_pkg_extension_discovery", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_shelf", ":dart_pkg_sse", ":dart_pkg_vm_service", ":dart_pkg_web_socket_channel", ":dart_pkg_webkit_inspection_protocol", ":dart_pkg_yaml", ":dart_pkg_yaml_edit"],
    )
    dart_library(
        name = "dart_pkg_dtd",
        srcs = native.glob(["pkg/dtd/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_dart_service_protocol_shared", ":dart_pkg_json_rpc_2", ":dart_pkg_stream_channel", ":dart_pkg_unified_analytics", ":dart_pkg_web_socket_channel"],
    )
    dart_library(
        name = "dart_pkg_dtd_impl",
        srcs = native.glob(["pkg/dtd_impl/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_dart_data_home", ":dart_pkg_dart_service_protocol_shared", ":dart_pkg_dds", ":dart_pkg_dtd", ":dart_pkg_file", ":dart_pkg_json_rpc_2", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_shelf", ":dart_pkg_shelf_web_socket", ":dart_pkg_sse", ":dart_pkg_stream_channel", ":dart_pkg_unified_analytics", ":dart_pkg_vm_service", ":dart_pkg_web_socket_channel"],
    )
    dart_library(
        name = "dart_pkg_dwds",
        srcs = native.glob(["pkg/dwds/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_dds", ":dart_pkg_file", ":dart_pkg_http", ":dart_pkg_http_multi_server", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_pub_semver", ":dart_pkg_shelf", ":dart_pkg_shelf_proxy", ":dart_pkg_shelf_web_socket", ":dart_pkg_source_maps", ":dart_pkg_sse", ":dart_pkg_stack_trace", ":dart_pkg_stream_channel", ":dart_pkg_vm_service", ":dart_pkg_vm_service_interface", ":dart_pkg_web_socket", ":dart_pkg_web_socket_channel", ":dart_pkg_webkit_inspection_protocol"],
    )
    dart_library(
        name = "dart_pkg_dwds_test_common",
        srcs = native.glob(["pkg/dwds_test_common/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_dwds", ":dart_pkg_file", ":dart_pkg_logging", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_dynamic_modules",
        srcs = native.glob(["pkg/dynamic_modules/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_engine",
        srcs = native.glob(["third_party/flute/engine/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_js", ":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_expect",
        srcs = native.glob(["pkg/expect/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_smith"],
    )
    dart_library(
        name = "dart_pkg_extension_discovery",
        srcs = native.glob(["third_party/pkg/tools/pkgs/extension_discovery/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_fake_async",
        srcs = native.glob(["third_party/pkg/test/pkgs/fake_async/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_clock", ":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_ffi",
        srcs = native.glob(["third_party/pkg/native/pkgs/ffi/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_file",
        srcs = native.glob(["third_party/pkg/tools/pkgs/file/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_file_testing",
        srcs = native.glob(["third_party/pkg/tools/pkgs/file_testing/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_fixnum",
        srcs = native.glob(["third_party/pkg/core/pkgs/fixnum/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_flute",
        srcs = native.glob(["third_party/flute/framework/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_characters", ":dart_pkg_collection", ":dart_pkg_engine", ":dart_pkg_material_color_utilities", ":dart_pkg_meta", ":dart_pkg_vector_math", ":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_flute_benchmarks",
        srcs = native.glob(["third_party/flute/benchmarks/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_engine", ":dart_pkg_flute"],
    )
    dart_library(
        name = "dart_pkg_flute_script",
        srcs = native.glob(["third_party/flute/script/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_file", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_platform", ":dart_pkg_process"],
    )
    dart_library(
        name = "dart_pkg_front_end",
        srcs = native.glob(["pkg/front_end/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg_kernel", ":dart_pkg_package_config", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_front_end_testcases",
        srcs = native.glob(["pkg/front_end/testcases/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_frontend_server",
        srcs = native.glob(["pkg/frontend_server/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_build_integration", ":dart_pkg_compiler", ":dart_pkg_dart2wasm", ":dart_pkg_dev_compiler", ":dart_pkg_front_end", ":dart_pkg_kernel", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_vm"],
    )
    dart_library(
        name = "dart_pkg_frontend_server_client",
        srcs = native.glob(["pkg/frontend_server_client/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_package_config", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_glob",
        srcs = native.glob(["third_party/pkg/tools/pkgs/glob/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_collection", ":dart_pkg_file", ":dart_pkg_path", ":dart_pkg_string_scanner"],
    )
    dart_library(
        name = "dart_pkg_graphs",
        srcs = native.glob(["third_party/pkg/tools/pkgs/graphs/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_heap_snapshot",
        srcs = native.glob(["pkg/heap_snapshot/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_heapsnapshot",
        srcs = native.glob(["runtime/tools/heapsnapshot/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_heap_snapshot", ":dart_pkg_mmap", ":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_hooks",
        srcs = native.glob(["third_party/pkg/native/pkgs/hooks/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_pub_semver", ":dart_pkg_record_use", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_hooks_runner",
        srcs = native.glob(["third_party/pkg/native/pkgs/hooks_runner/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_code_assets", ":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_file", ":dart_pkg_graphs", ":dart_pkg_hooks", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_pub_semver", ":dart_pkg_record_use", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_html",
        srcs = native.glob(["third_party/pkg/tools/pkgs/html/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_csslib", ":dart_pkg_source_span"],
    )
    dart_library(
        name = "dart_pkg_http",
        srcs = native.glob(["third_party/pkg/http/pkgs/http/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_http_parser", ":dart_pkg_meta", ":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_http2",
        srcs = native.glob(["third_party/pkg/http/pkgs/http2/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_httpIG_sample",
        srcs = native.glob(["samples/ffi/httpIG/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_ffi"],
    )
    dart_library(
        name = "dart_pkg_http_client_conformance_tests",
        srcs = native.glob(["third_party/pkg/http/pkgs/http_client_conformance_tests/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_dart_style", ":dart_pkg_http", ":dart_pkg_stream_channel", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_http_multi_server",
        srcs = native.glob(["third_party/pkg/http/pkgs/http_multi_server/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async"],
    )
    dart_library(
        name = "dart_pkg_http_parser",
        srcs = native.glob(["third_party/pkg/http/pkgs/http_parser/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_source_span", ":dart_pkg_string_scanner", ":dart_pkg_typed_data"],
    )
    dart_library(
        name = "dart_pkg_http_profile",
        srcs = native.glob(["third_party/pkg/http/pkgs/http_profile/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_http_sample",
        srcs = native.glob(["samples/ffi/http/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_ffi"],
    )
    dart_library(
        name = "dart_pkg_intl",
        srcs = native.glob(["third_party/pkg/i18n/pkgs/intl/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_clock", ":dart_pkg_meta", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_io",
        srcs = native.glob(["third_party/pkg/tools/pkgs/io/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_string_scanner"],
    )
    dart_library(
        name = "dart_pkg_js",
        srcs = native.glob(["pkg/js/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_js_ast",
        srcs = native.glob(["pkg/js_ast/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_js_runtime",
        srcs = native.glob(["pkg/js_runtime/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_js_shared",
        srcs = native.glob(["pkg/js_shared/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_json_rpc_2",
        srcs = native.glob(["third_party/pkg/tools/pkgs/json_rpc_2/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_stack_trace", ":dart_pkg_stream_channel"],
    )
    dart_library(
        name = "dart_pkg_kernel",
        srcs = native.glob(["pkg/kernel/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared"],
    )
    dart_library(
        name = "dart_pkg_language_server_protocol",
        srcs = native.glob(["third_party/pkg/language_server_protocol/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_leak_tracker",
        srcs = native.glob(["third_party/pkg/leak_tracker/pkgs/leak_tracker/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_clock", ":dart_pkg_collection", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_leak_tracker_testing",
        srcs = native.glob(["third_party/pkg/leak_tracker/pkgs/leak_tracker_testing/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_leak_tracker", ":dart_pkg_matcher", ":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_linter",
        srcs = native.glob(["pkg/linter/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_collection", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_source_span", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_lints",
        srcs = native.glob(["third_party/pkg/core/pkgs/lints/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_logging",
        srcs = native.glob(["third_party/pkg/core/pkgs/logging/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_markdown",
        srcs = native.glob(["third_party/pkg/tools/pkgs/markdown/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_matcher",
        srcs = native.glob(["third_party/pkg/test/pkgs/matcher/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_meta", ":dart_pkg_stack_trace", ":dart_pkg_term_glyph", ":dart_pkg_test_api"],
    )
    dart_library(
        name = "dart_pkg_material_color_utilities",
        srcs = native.glob(["third_party/pkg/material_color_utilities/dart/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_memory_usage",
        srcs = native.glob(["third_party/pkg/leak_tracker/pkgs/memory_usage/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_meta",
        srcs = native.glob(["pkg/meta/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_mime",
        srcs = native.glob(["third_party/pkg/tools/pkgs/mime/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_mmap",
        srcs = native.glob(["pkg/mmap/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_ffi"],
    )
    dart_library(
        name = "dart_pkg_modular_test",
        srcs = native.glob(["pkg/modular_test/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_package_config", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_native_compiler",
        srcs = native.glob(["pkg/native_compiler/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_cfg", ":dart_pkg_crypto", ":dart_pkg_front_end", ":dart_pkg_kernel", ":dart_pkg_path", ":dart_pkg_vm"],
    )
    dart_library(
        name = "dart_pkg_native_stack_traces",
        srcs = native.glob(["pkg/native_stack_traces/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_native_test_helpers",
        srcs = native.glob(["third_party/pkg/native/pkgs/native_test_helpers/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_native_toolchain_c",
        srcs = native.glob(["third_party/pkg/native/pkgs/native_toolchain_c/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_code_assets", ":dart_pkg_glob", ":dart_pkg_hooks", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_pub_semver"],
    )
    dart_library(
        name = "dart_pkg_node_preamble",
        srcs = native.glob(["pkg/node_preamble/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_oauth2",
        srcs = native.glob(["third_party/pkg/tools/pkgs/oauth2/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_http", ":dart_pkg_http_parser"],
    )
    dart_library(
        name = "dart_pkg_observatory",
        srcs = native.glob(["pkg/observatory/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_browser_launcher", ":dart_pkg_logging", ":dart_pkg_stack_trace", ":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_os_detect",
        srcs = native.glob(["third_party/pkg/core/pkgs/os_detect/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta", ":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_package_config",
        srcs = native.glob(["third_party/pkg/tools/pkgs/package_config/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_package_deps",
        srcs = native.glob(["tools/package_deps/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_cli_util", ":dart_pkg_collection", ":dart_pkg_path", ":dart_pkg_pub_semver", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_path",
        srcs = native.glob(["third_party/pkg/core/pkgs/path/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_perf_witness",
        srcs = native.glob(["pkg/perf_witness/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_dart_data_home", ":dart_pkg_ffi", ":dart_pkg_json_rpc_2", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_stream_channel"],
    )
    dart_library(
        name = "dart_pkg_platform",
        srcs = native.glob(["third_party/pkg/core/pkgs/platform/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_pool",
        srcs = native.glob(["third_party/pkg/tools/pkgs/pool/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_stack_trace"],
    )
    dart_library(
        name = "dart_pkg_process",
        srcs = native.glob(["third_party/pkg/tools/pkgs/process/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_file", ":dart_pkg_path", ":dart_pkg_platform"],
    )
    dart_library(
        name = "dart_pkg_profiling",
        srcs = native.glob(["runtime/tools/profiling/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_fixnum", ":dart_pkg_path", ":dart_pkg_protobuf"],
    )
    dart_library(
        name = "dart_pkg_protobuf",
        srcs = native.glob(["third_party/pkg/protobuf/protobuf/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_fixnum", ":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_protobuf_benchmarks",
        srcs = native.glob(["third_party/pkg/protobuf/benchmarks/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_benchmark_harness", ":dart_pkg_fixnum", ":dart_pkg_js", ":dart_pkg_protobuf"],
    )
    dart_library(
        name = "dart_pkg_protoc_plugin",
        srcs = native.glob(["third_party/pkg/protobuf/protoc_plugin/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_dart_style", ":dart_pkg_fixnum", ":dart_pkg_path", ":dart_pkg_protobuf", ":dart_pkg_pub_semver"],
    )
    dart_library(
        name = "dart_pkg_pub",
        srcs = native.glob(["third_party/pkg/pub/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_async", ":dart_pkg_cli_util", ":dart_pkg_collection", ":dart_pkg_convert", ":dart_pkg_crypto", ":dart_pkg_file", ":dart_pkg_frontend_server_client", ":dart_pkg_glob", ":dart_pkg_graphs", ":dart_pkg_http", ":dart_pkg_http_multi_server", ":dart_pkg_http_parser", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_pub_semver", ":dart_pkg_shelf", ":dart_pkg_source_span", ":dart_pkg_stack_trace", ":dart_pkg_tar", ":dart_pkg_typed_data", ":dart_pkg_web", ":dart_pkg_yaml", ":dart_pkg_yaml_edit"],
    )
    dart_library(
        name = "dart_pkg_pub_formats",
        srcs = native.glob(["third_party/pkg/native/pkgs/pub_formats/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_pub_semver",
        srcs = native.glob(["third_party/pkg/tools/pkgs/pub_semver/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_record_use",
        srcs = native.glob(["third_party/pkg/native/pkgs/record_use/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_meta", ":dart_pkg_pub_semver"],
    )
    dart_library(
        name = "dart_pkg_record_use_js_test",
        srcs = native.glob(["pkg/compiler/test/record_use/data/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_record_use_test",
        srcs = native.glob(["pkg/vm/testcases/transformations/record_use/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta"],
    )
    dart_library(
        name = "dart_pkg_regression_tests",
        srcs = native.glob(["third_party/pkg/test/integration_tests/regression/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_reload_test",
        srcs = native.glob(["pkg/reload_test/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_dev_compiler", ":dart_pkg_frontend_server", ":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_runtime_tests_vm_dart",
        srcs = native.glob(["runtime/tests/vm/dart/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_runtime_tools",
        srcs = native.glob(["runtime/tools/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_scrape",
        srcs = native.glob(["pkg/scrape/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_sdk_tools",
        srcs = native.glob(["tools/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_bisect_dart", ":dart_pkg_cli_util", ":dart_pkg_convert", ":dart_pkg_crypto", ":dart_pkg_glob", ":dart_pkg_http", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_pub_semver", ":dart_pkg_smith", ":dart_pkg_test_runner", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_server_plugin",
        srcs = native.glob(["pkg/server_plugin/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_shelf",
        srcs = native.glob(["third_party/pkg/shelf/pkgs/shelf/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_collection", ":dart_pkg_http_parser", ":dart_pkg_path", ":dart_pkg_stack_trace", ":dart_pkg_stream_channel"],
    )
    dart_library(
        name = "dart_pkg_shelf_packages_handler",
        srcs = native.glob(["third_party/pkg/shelf/pkgs/shelf_packages_handler/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_path", ":dart_pkg_shelf", ":dart_pkg_shelf_static"],
    )
    dart_library(
        name = "dart_pkg_shelf_proxy",
        srcs = native.glob(["third_party/pkg/shelf/pkgs/shelf_proxy/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_http", ":dart_pkg_path", ":dart_pkg_shelf"],
    )
    dart_library(
        name = "dart_pkg_shelf_static",
        srcs = native.glob(["third_party/pkg/shelf/pkgs/shelf_static/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_convert", ":dart_pkg_http_parser", ":dart_pkg_mime", ":dart_pkg_path", ":dart_pkg_shelf"],
    )
    dart_library(
        name = "dart_pkg_shelf_test_handler",
        srcs = native.glob(["third_party/pkg/shelf/pkgs/shelf_test_handler/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_http_multi_server", ":dart_pkg_shelf", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_shelf_web_socket",
        srcs = native.glob(["third_party/pkg/shelf/pkgs/shelf_web_socket/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_shelf", ":dart_pkg_stream_channel", ":dart_pkg_web_socket_channel"],
    )
    dart_library(
        name = "dart_pkg_shell_arg_splitter",
        srcs = native.glob(["pkg/shell_arg_splitter/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_smith",
        srcs = native.glob(["pkg/smith/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_source_map_stack_trace",
        srcs = native.glob(["third_party/pkg/tools/pkgs/source_map_stack_trace/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_path", ":dart_pkg_source_maps", ":dart_pkg_stack_trace"],
    )
    dart_library(
        name = "dart_pkg_source_maps",
        srcs = native.glob(["third_party/pkg/tools/pkgs/source_maps/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_source_span"],
    )
    dart_library(
        name = "dart_pkg_source_span",
        srcs = native.glob(["third_party/pkg/tools/pkgs/source_span/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_path", ":dart_pkg_term_glyph"],
    )
    dart_library(
        name = "dart_pkg_sourcemap_testing",
        srcs = native.glob(["pkg/sourcemap_testing/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg_dart2js_tools", ":dart_pkg_expect", ":dart_pkg_path", ":dart_pkg_source_maps", ":dart_pkg_source_span"],
    )
    dart_library(
        name = "dart_pkg_spawn_hybrid",
        srcs = native.glob(["third_party/pkg/test/integration_tests/spawn_hybrid/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_path", ":dart_pkg_stream_channel"],
    )
    dart_library(
        name = "dart_pkg_sse",
        srcs = native.glob(["third_party/pkg/tools/pkgs/sse/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_collection", ":dart_pkg_logging", ":dart_pkg_pool", ":dart_pkg_shelf", ":dart_pkg_stream_channel", ":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_stack_trace",
        srcs = native.glob(["third_party/pkg/tools/pkgs/stack_trace/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_status_file",
        srcs = native.glob(["pkg/status_file/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_stream_channel",
        srcs = native.glob(["third_party/pkg/tools/pkgs/stream_channel/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async"],
    )
    dart_library(
        name = "dart_pkg_stream_transform",
        srcs = native.glob(["third_party/pkg/tools/pkgs/stream_transform/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_string_scanner",
        srcs = native.glob(["third_party/pkg/tools/pkgs/string_scanner/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_source_span"],
    )
    dart_library(
        name = "dart_pkg_swift2objc",
        srcs = native.glob(["third_party/pkg/native/pkgs/swift2objc/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_logging", ":dart_pkg_meta", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_sync_http",
        srcs = native.glob(["third_party/pkg/sync_http/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_tar",
        srcs = native.glob(["third_party/pkg/tar/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_meta", ":dart_pkg_typed_data"],
    )
    dart_library(
        name = "dart_pkg_telemetry",
        srcs = native.glob(["pkg/telemetry/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_http", ":dart_pkg_meta", ":dart_pkg_stack_trace"],
    )
    dart_library(
        name = "dart_pkg_term_glyph",
        srcs = native.glob(["third_party/pkg/tools/pkgs/term_glyph/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_test",
        srcs = native.glob(["third_party/pkg/test/pkgs/test/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_async", ":dart_pkg_boolean_selector", ":dart_pkg_collection", ":dart_pkg_coverage", ":dart_pkg_http_multi_server", ":dart_pkg_io", ":dart_pkg_matcher", ":dart_pkg_node_preamble", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_shelf", ":dart_pkg_shelf_packages_handler", ":dart_pkg_shelf_static", ":dart_pkg_shelf_web_socket", ":dart_pkg_source_span", ":dart_pkg_stack_trace", ":dart_pkg_stream_channel", ":dart_pkg_test_api", ":dart_pkg_test_core", ":dart_pkg_typed_data", ":dart_pkg_web_socket_channel", ":dart_pkg_webkit_inspection_protocol", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_test_api",
        srcs = native.glob(["third_party/pkg/test/pkgs/test_api/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_boolean_selector", ":dart_pkg_collection", ":dart_pkg_meta", ":dart_pkg_source_span", ":dart_pkg_stack_trace", ":dart_pkg_stream_channel", ":dart_pkg_string_scanner", ":dart_pkg_term_glyph"],
    )
    dart_library(
        name = "dart_pkg_test_case_selector",
        srcs = native.glob(["third_party/pkg/native/pkgs/test_case_selector/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_meta", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_test_core",
        srcs = native.glob(["third_party/pkg/test/pkgs/test_core/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_analyzer", ":dart_pkg_args", ":dart_pkg_async", ":dart_pkg_boolean_selector", ":dart_pkg_collection", ":dart_pkg_coverage", ":dart_pkg_frontend_server_client", ":dart_pkg_glob", ":dart_pkg_io", ":dart_pkg_meta", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_source_map_stack_trace", ":dart_pkg_source_maps", ":dart_pkg_source_span", ":dart_pkg_stack_trace", ":dart_pkg_stream_channel", ":dart_pkg_test_api", ":dart_pkg_vm_service", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_test_descriptor",
        srcs = native.glob(["third_party/pkg/test/pkgs/test_descriptor/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_collection", ":dart_pkg_path", ":dart_pkg_term_glyph", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_test_package",
        srcs = native.glob(["pkg/vm_service/test/test_package/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_test_process",
        srcs = native.glob(["third_party/pkg/test/pkgs/test_process/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_meta", ":dart_pkg_path", ":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_test_reflective_loader",
        srcs = native.glob(["third_party/pkg/tools/pkgs/test_reflective_loader/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_test"],
    )
    dart_library(
        name = "dart_pkg_test_runner",
        srcs = native.glob(["pkg/test_runner/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_dart2js_tools", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_pool", ":dart_pkg_shell_arg_splitter", ":dart_pkg_smith", ":dart_pkg_status_file", ":dart_pkg_webdriver"],
    )
    dart_library(
        name = "dart_pkg_testing",
        srcs = native.glob(["pkg/testing/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_tests_ffi",
        srcs = native.glob(["tests/ffi/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_tool",
        srcs = native.glob(["third_party/pkg/webdev/tool/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_typed_data",
        srcs = native.glob(["third_party/pkg/core/pkgs/typed_data/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_unified_analytics",
        srcs = native.glob(["third_party/pkg/tools/pkgs/unified_analytics/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_clock", ":dart_pkg_convert", ":dart_pkg_file", ":dart_pkg_http", ":dart_pkg_meta", ":dart_pkg_platform"],
    )
    dart_library(
        name = "dart_pkg_utils",
        srcs = native.glob(["utils/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_vector_math",
        srcs = native.glob(["third_party/pkg/vector_math/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_verify_docs",
        srcs = native.glob(["tools/verify_docs/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg__fe_analyzer_shared", ":dart_pkg_analyzer", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_vm",
        srcs = native.glob(["pkg/vm/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_build_integration", ":dart_pkg_collection", ":dart_pkg_crypto", ":dart_pkg_front_end", ":dart_pkg_kernel", ":dart_pkg_package_config", ":dart_pkg_path", ":dart_pkg_record_use", ":dart_pkg_yaml"],
    )
    dart_library(
        name = "dart_pkg_vm_service",
        srcs = native.glob(["pkg/vm_service/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_vm_service_interface",
        srcs = native.glob(["pkg/vm_service_interface/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_vm_service"],
    )
    dart_library(
        name = "dart_pkg_vm_service_protos",
        srcs = native.glob(["pkg/vm_service_protos/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_fixnum", ":dart_pkg_protobuf"],
    )
    dart_library(
        name = "dart_pkg_vm_snapshot_analysis",
        srcs = native.glob(["pkg/vm_snapshot_analysis/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_args", ":dart_pkg_collection", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_wasm_builder",
        srcs = native.glob(["pkg/wasm_builder/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection"],
    )
    dart_library(
        name = "dart_pkg_wasm_tests",
        srcs = native.glob(["third_party/pkg/test/integration_tests/wasm/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_watcher",
        srcs = native.glob(["third_party/pkg/tools/pkgs/watcher/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_path"],
    )
    dart_library(
        name = "dart_pkg_web",
        srcs = native.glob(["third_party/pkg/web/web/lib/**/*.dart"], allow_empty = True),
        deps = [],
    )
    dart_library(
        name = "dart_pkg_web_socket",
        srcs = native.glob(["third_party/pkg/http/pkgs/web_socket/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_web_socket_channel",
        srcs = native.glob(["third_party/pkg/http/pkgs/web_socket_channel/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_async", ":dart_pkg_crypto", ":dart_pkg_stream_channel", ":dart_pkg_web", ":dart_pkg_web_socket"],
    )
    dart_library(
        name = "dart_pkg_webdriver",
        srcs = native.glob(["third_party/pkg/webdriver/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_matcher", ":dart_pkg_path", ":dart_pkg_stack_trace", ":dart_pkg_sync_http", ":dart_pkg_web"],
    )
    dart_library(
        name = "dart_pkg_webkit_inspection_protocol",
        srcs = native.glob(["third_party/pkg/webkit_inspection_protocol/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_logging"],
    )
    dart_library(
        name = "dart_pkg_yaml",
        srcs = native.glob(["third_party/pkg/tools/pkgs/yaml/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_source_span", ":dart_pkg_string_scanner"],
    )
    dart_library(
        name = "dart_pkg_yaml_edit",
        srcs = native.glob(["third_party/pkg/tools/pkgs/yaml_edit/lib/**/*.dart"], allow_empty = True),
        deps = [":dart_pkg_collection", ":dart_pkg_meta", ":dart_pkg_source_span", ":dart_pkg_yaml"],
    )
